//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailScale.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("butAccedi")]
        public string butIscriviti {
            get {
                return ((string)(this["butIscriviti"]));
            }
            set {
                this["butIscriviti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("butAccediLogIn")]
        public string butAccedi {
            get {
                return ((string)(this["butAccedi"]));
            }
            set {
                this["butAccedi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exitForm")]
        public string exitForm {
            get {
                return ((string)(this["exitForm"]));
            }
            set {
                this["exitForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("exitForm")]
        public string exit {
            get {
                return ((string)(this["exit"]));
            }
            set {
                this["exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string nomeReg {
            get {
                return ((string)(this["nomeReg"]));
            }
            set {
                this["nomeReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passReg {
            get {
                return ((string)(this["passReg"]));
            }
            set {
                this["passReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emailReg {
            get {
                return ((string)(this["emailReg"]));
            }
            set {
                this["emailReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ctrlEmailReg {
            get {
                return ((string)(this["ctrlEmailReg"]));
            }
            set {
                this["ctrlEmailReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cognomeReg {
            get {
                return ((string)(this["cognomeReg"]));
            }
            set {
                this["cognomeReg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("butRegistra")]
        public string butRegistra {
            get {
                return ((string)(this["butRegistra"]));
            }
            set {
                this["butRegistra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("butAccedi")]
        public string but_Accedi {
            get {
                return ((string)(this["but_Accedi"]));
            }
            set {
                this["but_Accedi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Accedi")]
        public string Accedi {
            get {
                return ((string)(this["Accedi"]));
            }
            set {
                this["Accedi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ctrlPassReg {
            get {
                return ((string)(this["ctrlPassReg"]));
            }
            set {
                this["ctrlPassReg"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Ferrovia.mdf;" +
            "Integrated Security=True;Connect Timeout=30")]
        public string FerroviaConnectionString {
            get {
                return ((string)(this["FerroviaConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("carro_btn")]
        public string pesatura_btn {
            get {
                return ((string)(this["pesatura_btn"]));
            }
            set {
                this["pesatura_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("treni_btn")]
        public string treni_btn {
            get {
                return ((string)(this["treni_btn"]));
            }
            set {
                this["treni_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("products_btn")]
        public string prodotto_btn {
            get {
                return ((string)(this["prodotto_btn"]));
            }
            set {
                this["prodotto_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("saluta_utente")]
        public string saluta_utente {
            get {
                return ((string)(this["saluta_utente"]));
            }
            set {
                this["saluta_utente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("carro_btn")]
        public string carro_btn {
            get {
                return ((string)(this["carro_btn"]));
            }
            set {
                this["carro_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rails_btn")]
        public string rails_btn {
            get {
                return ((string)(this["rails_btn"]));
            }
            set {
                this["rails_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("products_btn")]
        public string products_btn {
            get {
                return ((string)(this["products_btn"]));
            }
            set {
                this["products_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("secPesa_btn")]
        public string secPesa_btn {
            get {
                return ((string)(this["secPesa_btn"]));
            }
            set {
                this["secPesa_btn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("editCarro")]
        public string editCarro {
            get {
                return ((string)(this["editCarro"]));
            }
            set {
                this["editCarro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cancCarro")]
        public string cancDati {
            get {
                return ((string)(this["cancDati"]));
            }
            set {
                this["cancDati"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("comboBoxProdotto")]
        public string comboBoxProdotto {
            get {
                return ((string)(this["comboBoxProdotto"]));
            }
            set {
                this["comboBoxProdotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("comboBoxIdCarro")]
        public string comboBoxIdCarro {
            get {
                return ((string)(this["comboBoxIdCarro"]));
            }
            set {
                this["comboBoxIdCarro"] = value;
            }
        }
    }
}
